### ISSUE TITLE
Javascript config not found

### ISSUE THREAD

**Issue by AndreiDumitran** [thenbe/neotest-playwright#13]
Hello, I know it might be weird but my company uses playwright with javascript instead of typescript.
I have tried this option but it seems it's looking just for javascript configs. 
```
 get_playwright_config = function()
            return vim.loop.cwd() + "/playwright.config.js"
          end,
```
Is there any possibility to support javascript configs?
Thanks!

**Comment by thenbe** [comment]
It should now look for both ts and js extensions by default.
