### ISSUE TITLE
pickers.lua throws an error for telescope installation when the option is disabled

### ISSUE THREAD

**Issue by oedotme** [thenbe/neotest-playwright#38]
Telescope installation is optional (and experimental), but causes the adapter to fail if it's not installed.

Could it be possible to throw error only if the option is enabled?

https://github.com/thenbe/neotest-playwright/blob/f61463f5c74d53fc5975b7e086b7c6e9356d9215/src/pickers.lua#L3-L5

`→`

```lua
if not has_telescope then
  if options.experimental.telescope.enabled then error('nvim-telescope/telescope.nvim is not installed') end
  return
end

```

**Comment by thenbe** [comment]
Now, it should only show an error if `experimental.telescope.enabled = true`.
