### ISSUE TITLE
automatic releases and luarocks/rocks.nvim support?

### ISSUE THREAD

**Issue by mrcjkb** [thenbe/neotest-playwright#40]
Hey :wave:

[rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) has the ability to install luarocks packages and automatically install dependencies, including tree-sitter parsers.

I was wondering: Would you be open to automating releases and publishing this plugin to luarocks.org?
See also [our wiki page on plugin support](https://github.com/nvim-neorocks/rocks.nvim/wiki/Plugin-support).

I'd be more than happy to help if you have any questions or issues.

**Comment by thenbe** [comment]
Hi 👋

I was actually looking for something like this when I was creating this project. Having access to luarocks dependencies would've been very helpful. I'll probably look into adopting this during the next refactor.

Thanks for the notice.
